# Do not edit. Generated by the configure script.
{
  "variables": {
    "host_arch": "ia32", 
    "luvit_debug": "false", 
    "luvit_prefix": "", 
    "target_arch": "ia32"
  }, 
  "target_defaults": {
    "libraries": [], 
    "defines": [], 
    "cflags": [], 
    "include_dirs": []
  }
}
