return {
  name = "luvit/luvit",
  version = "1.9.5",
  dependencies = {
    "luvit/buffer@0.1.0",
    "luvit/childprocess@0.1.0",
    "luvit/codec@0.1.1",
    "luvit/core@0.1.1",
    "luvit/dgram@0.1.2",
    "luvit/dns@0.1.1",
    "luvit/fs@0.1.3",
    "luvit/helpful@0.1.1",
    "luvit/hooks@0.1.0",
    "luvit/http@0.1.4",
    "luvit/http-codec@0.1.5",
    "luvit/https@0.1.3",
    "luvit/json@0.1.0",
    "luvit/los@0.1.0",
    "luvit/net@0.1.1",
    "luvit/path@0.1.0",
    "luvit/pretty-print@0.1.1",
    "luvit/process@0.1.2",
    "luvit/querystring@0.1.1",
    "luvit/readline@0.1.0",
    "luvit/repl@0.1.2",
    "luvit/require@0.2.4",
    "luvit/stream@0.1.1",
    "luvit/timer@0.1.0",
    "luvit/tls@0.1.1",
    "luvit/utils@0.1.0",
    "luvit/url@0.1.1",
  },
  files = {
    "*.lua",
    "!examples",
    "!tests",
    "!bench",
    "!lit-*",
  },
}


