local UV = require('uv');

UV.fs_open("license.txt", 'r', "0644", function (fd)
  p("on_open", {fd=fd})
  UV.fs_read(fd, 0, 4096, function (chunk, length)
    p("on_read", {chunk=chunk, length=length})
    UV.fs_close(fd, function ()
      p("on_close")
    end)
  end)
end)

UV.fs_mkdir("temp", "0755", function ()
  p("on_mkdir")
  UV.fs_rmdir("temp", function ()
    p("on_rmdir")
  end)
end)

UV.fs_open("tempfile", "w", "0644", function (fd)
  p("on_open2", {fd=fd})
  UV.fs_write(fd, 0, "Hello World\n", function (bytes_written)
    p("on_write", {bytes_written=bytes_written})
    UV.fs_close(fd, function ()
      p("on_close2")
      UV.fs_unlink("tempfile", function ()
        p("on_unlink")
      end)
    end)
  end)
end)
