local FS = require('fs');

FS.open("license.txt", 'r', "0644", function (fd)
  p("on_open", {fd=fd})
  FS.read(fd, 0, 4096, function (chunk, length)
    p("on_read", {chunk=chunk, length=length})
    FS.close(fd, function ()
      p("on_close")
    end)
  end)
end)

FS.mkdir("temp", "0755", function ()
  p("on_mkdir")
  FS.rmdir("temp", function ()
    p("on_rmdir")
  end)
end)

FS.open("tempfile", "w", "0644", function (fd)
  p("on_open2", {fd=fd})
  FS.write(fd, 0, "Hello World\n", function (bytes_written)
    p("on_write", {bytes_written=bytes_written})
    FS.close(fd, function ()
      p("on_close2")
      FS.unlink("tempfile", function ()
        p("on_unlink")
      end)
    end)
  end)
end)
