local Process = require('process')

local child = Process:spawn("ls", {"-l"}, {cwd="/etc"})
--local child = Process.spawn("sh", {"env.sh"}, {env={"FOO=true","BAR=42"}})
child:on('exit', function (exit_status, term_signal)
  p("on_exit", {exit_status=exit_status, term_signal=term_signal})
end)
child.stdout:on("data", function (chunk, len)
  p("on_stdout_data", {chunk=chunk,len=len})
end)
child.stderr:on("data", function (chunk, len)
  p("on_stderr_data", {chunk=chunk,len=len})
end)
child.stdout:on('finish', function ()
  p("on_stdout_end")
end)
child.stderr:on('finish', function ()
  p("on_stderr_end")
end)

