/* This file is generated by bundler.lua */
#include <string.h>
#include "luvit.h"

const void *luvit_ugly_hack = NULL;

extern const char **luaJIT_BC_buffer;
extern const char **luaJIT_BC_childprocess;
extern const char **luaJIT_BC_core;
extern const char **luaJIT_BC_dns;
extern const char **luaJIT_BC_fiber;
extern const char **luaJIT_BC_fs;
extern const char **luaJIT_BC_http;
extern const char **luaJIT_BC_json;
extern const char **luaJIT_BC_luvit;
extern const char **luaJIT_BC_mime;
extern const char **luaJIT_BC_net;
extern const char **luaJIT_BC_path;
extern const char **luaJIT_BC_pipe;
extern const char **luaJIT_BC_querystring;
extern const char **luaJIT_BC_repl;
extern const char **luaJIT_BC_stack;
extern const char **luaJIT_BC_tcp;
extern const char **luaJIT_BC_timer;
extern const char **luaJIT_BC_tty;
extern const char **luaJIT_BC_udp;
extern const char **luaJIT_BC_url;
extern const char **luaJIT_BC_utils;

const void *luvit__suck_in_symbols(void)
{
  luvit_ugly_hack = (const char*)

    (size_t)(const char *)luaJIT_BC_buffer +
    (size_t)(const char *)luaJIT_BC_childprocess +
    (size_t)(const char *)luaJIT_BC_core +
    (size_t)(const char *)luaJIT_BC_dns +
    (size_t)(const char *)luaJIT_BC_fiber +
    (size_t)(const char *)luaJIT_BC_fs +
    (size_t)(const char *)luaJIT_BC_http +
    (size_t)(const char *)luaJIT_BC_json +
    (size_t)(const char *)luaJIT_BC_luvit +
    (size_t)(const char *)luaJIT_BC_mime +
    (size_t)(const char *)luaJIT_BC_net +
    (size_t)(const char *)luaJIT_BC_path +
    (size_t)(const char *)luaJIT_BC_pipe +
    (size_t)(const char *)luaJIT_BC_querystring +
    (size_t)(const char *)luaJIT_BC_repl +
    (size_t)(const char *)luaJIT_BC_stack +
    (size_t)(const char *)luaJIT_BC_tcp +
    (size_t)(const char *)luaJIT_BC_timer +
    (size_t)(const char *)luaJIT_BC_tty +
    (size_t)(const char *)luaJIT_BC_udp +
    (size_t)(const char *)luaJIT_BC_url +
    (size_t)(const char *)luaJIT_BC_utils;

  return luvit_ugly_hack;
}
